In [ ]:
%conda install numpy

In [ ]:
import numpy as np

arr1d = np.array([1,2,3])

print(arr1d) 
print(arr1d.shape)    # 형태
print(arr1d.ndim)     # 차원
print(arr1d.dtype)    # 타입

[1 2 3]
(3,)
1
int64


In [ ]:
import numpy as np

arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [7]:
import numpy as np

arr3d = np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])

print(arr3d)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
zero_all = np.zeros((3,4))  # zeros() 모두 0로
print(zero_all)

one_all = np.ones((2,3))    # ones() 모두 1로
print(one_all)

full_arr = np.full((2,2),7)   # full() 모두 ()안의 값으로
print(full_arr)

eye_arr = np.eye(4)       # 단위행렬: 행렬 곱셈에서 ‘1’ 역할을 하는 행렬
print(eye_arr)

diag_arr = np.diag([1,2,3,4])   # 대각선 행렬 생성
print(diag_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
arr_arange = np.arange(10)   # 1~9 정수 배열
print(arr_arange)

arr_arange2 = np.arange(5, 15, 2)   # 5~15
print(arr_arange2)

arr_linspace = np.linspace(0, 1, 5)
print(f"linspace(0, 1, 5): {arr_linspace}")

arr_linspace2 = np.linspace(0, 100, 11)
print(f"linspace(0, 100, 11): {arr_linspace2}")

arr_logspace = np.logspace(0, 3, 4)
print(f"logspace(0, 3, 4): {arr_logspace}")


[0 1 2 3 4 5 6 7 8 9]
[ 5  7  9 11 13]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
linspace(0, 100, 11): [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
logspace(0, 3, 4): [   1.   10.  100. 1000.]


In [34]:
np.random.seed()

rand_uniform = np.random.rand(3,3)
print(rand_uniform)

rand_normal = np.random.randn(3,3)
print(rand_normal)

rand_int = np.random.randint(0, 10, size=(3, 3))
print(rand_int)

choices = np.random.choice(['A', 'B', 'C', 'D'], size=5)
print(f"\n무작위 선택: {choices}")


[[0.59505968 0.93714539 0.69117665]
 [0.50096408 0.47162878 0.4020266 ]
 [0.37855759 0.59399383 0.71849332]]
[[ 1.7233592   0.04017802  0.60673976]
 [ 0.57599405  0.44795626 -0.55548513]
 [ 1.011729   -1.02555375 -0.22979604]]
[[6 9 8]
 [8 2 6]
 [5 6 8]]

무작위 선택: ['A' 'C' 'C' 'B' 'A']


In [35]:
arr_float32 = np.array([1, 2, 3], dtype=np.float32)
print(f"float32 배열: {arr_float32}, dtype: {arr_float32.dtype}")

arr_complex = np.array([1, 2, 3], dtype=np.complex128)
print(f"complex128 배열: {arr_complex}, dtype: {arr_complex.dtype}")

arr_int = np.array([1.7, 2.3, 3.9])
arr_converted = arr_int.astype(np.int32)
print(f"\n원본 (float): {arr_int}")
print(f"변환 (int32): {arr_converted}")

float32 배열: [1. 2. 3.], dtype: float32
complex128 배열: [1.+0.j 2.+0.j 3.+0.j], dtype: complex128

원본 (float): [1.7 2.3 3.9]
변환 (int32): [1 2 3]


In [39]:
arr = np.arange(12)
print(f"원본 배열: {arr}")

arr_3x4 = arr.reshape(3, 4)
print(f"\nreshape(3, 4):\n{arr_3x4}")

arr_2x6 = arr.reshape(2, 6)
print(f"\nreshape(2, 6):\n{arr_2x6}")

arr_2x2x3 = arr.reshape(2, 2, 3)
print(f"\nreshape(2, 2, 3):\n{arr_2x2x3}")

arr_auto = arr.reshape(4, -1)
print(f"\nreshape(4, -1) -> shape: {arr_auto.shape}")

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

reshape(2, 2, 3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

reshape(4, -1) -> shape: (4, 3)


In [69]:
# [과제 1] 1부터 100까지의 숫자 중 3의 배수만 포함하는 배열 생성
# 힌트: np.arange와 step 활용

test_1 = np.arange(3,101,3)  # (np.arrange(1,101,3)-1)[1:]
print(test_1)

# [과제 2] 5x5 체크보드 패턴 생성 (0과 1이 번갈아 나타남)
# 힌트: zeros로 시작, 슬라이싱으로 값 채우기

test_2 = np.zeros( (5,5) )
test_2[::2, 1::2] = 1
test_2[1::2, ::2] = 1
print(test_2)

# [과제 3] 평균이 50, 표준편차가 10인 정규분포에서 1000개 샘플 추출 후
#          기본 통계량(평균, 표준편차, 최소, 최대) 출력
# 힌트: np.random.normal 사용

test_3 = np.random.normal(loc=50,scale=10,size=1000)
test_3.mean(), test_3.std(), test_3.min(), test_3.max()


[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


(np.float64(49.65040957691756),
 np.float64(10.230333576487379),
 np.float64(22.87387436189562),
 np.float64(85.29055187570484))

In [ ]:
np.random.rand(3,2)    # 균등 분포는 양수값

array([[0.72781821, 0.7915775 ],
       [0.89938839, 0.59013521],
       [0.39591982, 0.30565557]])

In [ ]:
np.random.randn(2,4)   # 정규분포는 음수도 포함

array([[ 1.22519917, -0.06659147,  0.02171539,  0.59186291],
       [ 0.85247011, -0.92160888,  0.31508216, -2.38188956]])

In [64]:
np.random.seed(42)

a = (np.random.rand(100)*10).astype(np.int32)
a.mean()      # mean() 평균

np.float64(4.2)

In [ ]:
samples = np.array([np.random.randint(50,100) for i in range(100)])
(samples > 80) | (samples < 85)   

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [80]:
samples[ [0,int(len(samples)/2),-1] ]

array([52, 87, 87])

In [ ]:
sam = np.array([True,True,False])
~sam   # 여러개일떄는 not 불가 대신 ~

array([False, False,  True])

In [85]:
samples = np.random.rand(2,3)
print(samples.shape)
samples

(2, 3)


array([[0.6152282 , 0.44318008, 0.63269604],
       [0.86287928, 0.07985642, 0.77798443]])

In [88]:
samples.T[1,1] = 0.15

samples

array([[0.6152282 , 0.44318008, 0.63269604],
       [0.86287928, 0.15      , 0.77798443]])

In [95]:
samples = np.random.rand(2,3)
print(samples.shape)
samples

(2, 3)


array([[0.17826178, 0.98644773, 0.71507637],
       [0.61464112, 0.04703905, 0.87911022]])

In [98]:
copy_sam = samples.copy()
copy_sam[0,0] = 0.11

In [99]:
copy_sam

array([[0.11      , 0.98644773, 0.71507637],
       [0.61464112, 0.04703905, 0.87911022]])

In [ ]:
list_a = [1,2,3,4,5]
list_b = list_a[1:3]
list_b[0] = 100
print(list_a)

# 리스트는 슬라이싱 해서 가져올 경우 원본 변화 없음

[1, 2, 3, 4, 5]


In [ ]:
list_a = np.array([1,2,3,4,5])
list_b = list_a[1:3]
list_b[0] = 100
print(list_a)

# 넘파이는 슬라이싱 해서 가져오면 원본 변화

[  1 100   3   4   5]


In [ ]:
list_a = np.array([1,2,3,4,5])
list_b = list_a[1:3].copy()
list_b[0] = 100
print(list_a)

# copy() 함수로 복사 명시 해야 원본 변화 없음

[1 2 3 4 5]


In [ ]:
list_a = np.array([1,2,3,4,5])
list_b = list_a[1]
list_b = 100
print(list_a)

# 인덱싱의 경우 원본 변화 없음

[1 2 3 4 5]


In [ ]:
list_a = np.array([True,True,False])
list_b = list_a[0,2]
list_b = False
print(list_a)

[ True  True False]


In [ ]:
arr = [1, 2, 3, 4, 5]  
twos = [2, 2, 2, 2, 2]
result = []
for i in range(len(arr)):
    result.append(arr[i] + twos[i])



[1, 2, 3, 4, 5, 2, 2, 2, 2, 2]

In [119]:
sample_1 = np.arange(12).reshape(3,4)
print(sample_1)
sample_2 = np.arange(4)
print(sample_2)

sample_1 + sample_2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]


array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [126]:
left_sample = np.array([np.random.randint(10) for i in range(12)]).reshape(3,4)
right_sample = np.array(range(1)).reshape(1,1)
print(left_sample)
print(right_sample)
left_sample + right_sample

[[9 1 4 3]
 [8 3 7 7]
 [5 5 7 9]]
[[0]]


array([[9, 1, 4, 3],
       [8, 3, 7, 7],
       [5, 5, 7, 9]])

In [125]:
left_sam = np.random.choice(range(100),size=(2,3,4))
right_sam = np.random.choice(range(6),size=(2,3,1))
print(left_sam, right_sam)

left_sam + right_sam

[[[58 84 27 57]
  [19 33  4 81]
  [59 42 56 56]]

 [[74 53 80 44]
  [85 36 83 47]
  [53 47  5 33]]] [[[5]
  [5]
  [3]]

 [[4]
  [3]
  [0]]]


array([[[63, 89, 32, 62],
        [24, 38,  9, 86],
        [62, 45, 59, 59]],

       [[78, 57, 84, 48],
        [88, 39, 86, 50],
        [53, 47,  5, 33]]])

In [131]:
sample_1 = np.arange(4).reshape(4,1)
sample_2 = np.arange(3)
print(sample_1.shape, right_sample.shape)

sample_1 + sample_2

(4, 1) (1, 1)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
# 행렬 스칼라 -- 가능!
# 행렬(a,b,c) 1이 없는 경우 -- 확장대상이 되는 차수의 크기가 한개이상 맞고 나머지는 1로
# (1,x) or (x,1) 이면 오른쪽 1의 위치가 같아야 함
# (4,1) -->*(x,1)
# (1,4) -->*(1,x)  

In [138]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(arr + 10)
print(arr*2)
print(arr/2)
print(arr**2)

arr2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr2d*2)

[1 2 3 4 5]
[11 12 13 14 15]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[[ 2  4  6]
 [ 8 10 12]]


In [145]:
arr2d = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
arr1d = np.array([10,20,30])

print(arr2d + arr1d)
print(arr2d * arr1d)

print(arr2d.shape,arr1d.shape )
arr2d + arr1d

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]
(3, 3) (3,)


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [150]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
col_vector = np.array([[10],[20],[30]])

print(arr2d + col_vector)

arr1d = np.array([10,20,30])
arr1d.reshape(-1,1)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


array([[10],
       [20],
       [30]])

In [ ]:
row= np.array([1,2,3])
col = ([[10],[20],[30]])

print(col*row)
np.outer([10,20,30],[1,2,3])

[[10 20 30]
 [20 40 60]
 [30 60 90]]


array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [151]:
combinations = [
    ((3, 4), (4,)),
    ((3, 4), (1, 4)),
    ((3, 4), (3, 1)),
    ((5, 3, 4), (3, 4)),
    ((5, 3, 4), (1, 4)),
    ((5, 1, 4), (3, 1)),
]

for shape1, shape2 in combinations:
    result_shape = np.broadcast_shapes(shape1, shape2)
    print(f"  {shape1} + {shape2} → {result_shape}")

  (3, 4) + (4,) → (3, 4)
  (3, 4) + (1, 4) → (3, 4)
  (3, 4) + (3, 1) → (3, 4)
  (5, 3, 4) + (3, 4) → (5, 3, 4)
  (5, 3, 4) + (1, 4) → (5, 3, 4)
  (5, 1, 4) + (3, 1) → (5, 3, 4)


In [153]:
incompatible = [
    ((3, 4), (5,)),
    ((3, 4), (2, 3)),
    ((5, 3, 4), (2, 4)),
]

for shape1,shape2 in incompatible:
    try:
        np.broadcast_shapes(shape1,shape2)
    except ValueError as e:
        print(f"  {shape1} + {shape2} → Error!")



  (3, 4) + (5,) → Error!
  (3, 4) + (2, 3) → Error!
  (5, 3, 4) + (2, 4) → Error!


In [154]:
data = np.array([[65, 70, 75],
                 [80, 85, 90],
                 [70, 75, 80]])

print(data)

mean = data.mean(axis=0)
std = data.std(axis=0)
print(mean, std)

[[65 70 75]
 [80 85 90]
 [70 75 80]]
[71.66666667 76.66666667 81.66666667] [6.23609564 6.23609564 6.23609564]


In [ ]:
stu = np.array([np.random.randint(60,100) for i in range(20)])
over_60_stu = stu[stu >= 60]
np.where(over_60_stu >= 80, 'A',
         over_60_stu >= 70, 'B',
         over_60_stu, 'C')

TypeError: where() takes from 1 to 3 positional arguments but 6 were given

In [158]:
sam = np.array(['1','2','3','4'])
np.where(sam == '1','ok','not ok')

array(['ok', 'not ok', 'not ok', 'not ok'], dtype='<U6')

In [163]:
num = np.arange(36).reshape(6,6)
num

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
num[:3,:3], num[:3,-3:], num[3:,:3], num[3:,-3:]

# num[a:b, a2,b2]

(array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]]))

numpy 정리
- 수학의 행렬 대열을 바로 적용하게 해줌

In [ ]:
# 연산
# 브로드캐스팅 공식
# 카피
# 0차원 - 스칼라
# 1차원 - 벡터
# 2차원 - 행렬
# 3차원 - 텐서
# n차원 - n차원
# 다차원 배열을 쉽게 컨트롤
# 팬시 인덱싱
# 불 인덱싱
# np.where
# 불 인덱싱 & 불 인덱싱
# 불 인덱싱 | 불 인덱싱
# np.any()   np.all
